package com.app.service;

import com.app.model.JmProject;
import com.app.repository.JmProjectRepository;
import org.springframework.stereotype.Service;

import java.util.List;

@Service
public class JmProjectService {
    
    private final JmProjectRepository repository;
    
    public JmProjectService(JmProjectRepository repository) {
        this.repository = repository;
    }
    
    public JmProject createProject(JmProject project) {
        // The code will be auto-generated by the database
        return repository.save(project);
    }
    
    public List<JmProject> getAllProjects() {
        return repository.findAll();
    }
    
    public List<JmProject> getProjectsByStatus(String status) {
        return repository.findByStatus(status);
    }
}